name: ssh_file_downloader
description: A Flutter app to SSH into a PC and download files via SFTP.
version: 1.0.0+1

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.6.0
  path_provider: ^2.1.2
  file_selector: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
